# Generated by Django 3.2.8 on 2021-11-03 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_company_mobile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
    ]
