# Generated by Django 3.2.8 on 2021-11-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=100)),
                ('cust_address', models.CharField(max_length=100)),
                ('cust_phno', models.CharField(max_length=50)),
                ('cust_email', models.EmailField(max_length=200)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
